### ISSUE TITLE
Deck save spamming messes browser history

### ISSUE THREAD

**Issue by IhToN** [juandjara/cards-against#11]
When you are creating a new deck, each time you press the Save button it sends a "history.push" event, having to press Cancel as many times as you have pressed the save button.

**Comment by IhToN** [comment]
Fixed on commit https://github.com/IhToN/cards-against/commit/26bd293beba4ebbda945b0d9e680df8f7a4647b3

**Comment by juandjara** [comment]
I think it is easeir to do
```
if (deckIsNew) {
  navigate(`/decks/${id}`)
}
```

But this other solution is also fine

**Comment by IhToN** [comment]
Oh, I did not know about that parameter, then yep, I'll change the fix 😄
